### ISSUE TITLE
Torrent client fails to shutdown

### ISSUE THREAD

**Issue by JonathanNogueira** [AcademicTorrents/python-r-api#1]
The client fails to shutdown when downloading multiple file torrents.

**Comment by ronaldegmar** [comment]
Hi Jonathan,

I'd love to help you. However, I've been very busy lately.
I find myself in this time of my life looking again for a job.
Well, what to do? Just to keep going.
Maybe If I get some time later I might see the problem of the bittorrent
client.

Ronald

2017-11-27 15:13 GMT-05:00 Jonathan Nogueira <notifications@github.com>:

**Comment by ieee8023** [comment]
Nogueira, Can you push the current code (the repo code is empty) and write a test case so it will fail? From there it will be possible for someone to issue a pull request.

**Comment by ronaldegmar** [comment]
Hi Jonathan,

I didn't hear anything more from you about this.
By the way, I'm located in Massachusetts again. I'm working in a remote
DevOps position for Cornell University.

Regards,

Ronald Barrios

2017-11-28 12:59 GMT-05:00 Joseph Paul Cohen <notifications@github.com>:

**Comment by JonathanNogueira** [comment]
Hi Ronald , 

Sorry about not getting back to this. I had a crazy end of the year. 

The python torrent client being used seems to have an issue writing the last file when the torrent has multiple files. This is causing the last blocks to never pass verification keeping the client running and requesting the block again. 

Jonathan

**Comment by ronaldegmar** [comment]
Hi Jonathan,

How’s the academic torrents team going?
Is Professor Fletcher still working with you?
I would be glad to work as part of a project.
Maybe we can meet and talk some day.
Let me know. I’m available on regular working days at nights for a talk.
Otherwise, Saturdays still look fine to me.

Regards,

Ronald Barrios

**Comment by ieee8023** [comment]
This is for the old client
